# Site settings
title: Eugene Chiong
introduction: Hi, I'm Eugene Chiong 
description: A software engineer living in the Bay Area, I build stuff in my spare time, take photos, or go out and try new things.
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Eugene Chiong'
  email: me@eugene.codes
  twitter_username: eugenecys
  facebook_username: eugenecys
  github_username:  eugenecys
  linkedin_username:  eugenecys

defaults:
  -
    scope:
      path: ''
      type: 'default'
    values:
        layout: 'default'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
